name: Debt

on:
  push:
    branches: [ '*' ]

jobs:
  lint:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: install go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: check debt
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58
          working-directory: 'debt/src'
  build:
    runs-on: [ ubuntu-latest ]
    needs: [ lint ]
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: Build image
        run: docker build -t debt ./debt/
