name: Nebo

on:
  push:
    branches: [ '*' ]

jobs:
  lint:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: install python
        uses: actions/setup-python@v1
        with:
          python-version: 3.12
      - name: check nebolive
        uses: jpetrucciani/ruff-check@main
        with:
          path: './nebolive-gateway-api/src'

  build:
    runs-on: [ ubuntu-latest ]
    needs: [ lint ]
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: Build image
        run: docker build -t nebo -f Dockerfile nebolive-gateway-api
