name: Nebo

on:
  push:
    branches: [ '*' ]
    paths: [ 'nebolive-gateway-api/**' ]
  pull_request:

jobs:
  lint_nebo:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: install python
        uses: actions/setup-python@v1
        with:
          python-version: 3.12
      - name: check nebolive
        uses: jpetrucciani/ruff-check@main
        with:
          path: './nebolive-gateway-api/src'
